    @startuml
    class 馆藏目录{

    }
    class 馆藏资源品种{
        资源名称
        国际出版号
        价格
        简介
        馆藏数量
        可借数量
    }
    class 碟片品种{
        碟片类型
        碟片数
        制作公司
    }
    class 图书品种{
        作者
        出版社
        出版日期
    }
    class 预定记录{
        预定日期
    }
    class 资源项{
        馆藏流水号
        状态
    }
    class 借书记录{
        借书日期
        归还日期
    }
    class 读者{
        姓名
        身份证号
        借书卡号
        图书限额
        已借图书数
        碟片限额
        已借碟片数
    }
    class 教师读者{
        查看学生借书情况()
    }
    class 学生读者{
    }
    class 图书管理员{
        职工号
        姓名
    }
    class 教师图书管理员{

    }
    class 学生管理员{
    }
    class 逾期记录{
        逾期天数
    }
    class 罚款细则{
    }
    class 系统管理员{
        职工号
        姓名
        图书管理()
        管理员管理()
        读者管理()
    }
    馆藏目录 "1" --right"1..*" 馆藏资源品种
    馆藏资源品种 "1" --up "*" 预定记录:被预定
    预定记录 "*" --down "1" 读者
    馆藏资源品种 "1"*--right "*"资源项:拥有
    馆藏资源品种 o--down 碟片品种
    馆藏资源品种 o--down 图书品种
    资源项 "1"--down "0..1"借书记录
    读者 --left 借书记录
    图书管理员 "1"--right"*" 借书记录:登记
    借书记录 "1"--down "0..1" 逾期记录
    逾期记录 "*"--right"0..1" 罚款细则:使用
    读者 o-- 学生读者
    读者 o-- 教师读者
    图书管理员 o-- 教师图书管理员
    图书管理员 o-- 学生管理员
    图书管理员 o-- 系统管理员
    @enduml