@startuml
    object 读者 {
        姓名="杨双友"
        身份证号=320320320
        借书卡号=201510414323
        借书限额=5
        可借限额=3
    }
    object 借书记录{
        借书日期=2018-04-16
        应还日期=2018-05-16
        还书日期=2018-05-06
    }
    object 图书{
        馆藏流水号=20180416
        状态="借出"
    }
    object 图书品种{
        书名="信息系统分析与设计"
        作者="王晓敏 邝孔武"
        出版社="清华大学出版社"
        出版日期=2017.2
        ISBN="978-7-302-32982-4"
        价格=38.00元
    }
    object 图书管理员{
        职工号=000001
        姓名="吴彦祖"
    }
    读者 -- 借书记录
    图书品种 -- 图书
    图书 -- 借书记录
    图书管理员 -- 借书记录
    @enduml