    @startuml
    object 读者{
        姓名
        身份证号
        借书卡号
        图书限额
        已借图书数
        碟片限额
        已借碟片数
    }
    object 学生读者{
        姓名="杨双友"
        身份证号=320320320
        借书卡号=201510414323
        图书限额=7
        已借图书数=3
        碟片限额=3
        已借碟片数=1
    }
    object 教师读者{
        姓名="赵卫东"
        身份证号=123456789
        借书卡号=123456
        图书限额=15
        已借图书数=5
        碟片限额=20
        已借碟片数=5
    }
    读者 <|-- 学生读者
    读者 <|-- 教师读者
    教师读者 "1"--left"1..*" 学生读者:查看学生借书情况
    @enduml