    @startuml
    object 图书管理员{
        职工号
        姓名
    }
    object 学生图书管理员{
        身份证号=1314520
        姓名="杨二友"
    }
    object 教师图书管理员{
        职工号=147258369
        姓名=赵卫东
    }
    object 系统管理员{
        职工号=255255255
        姓名="小芳"
    }
    图书管理员 <|-- 学生图书管理员
    图书管理员 <|-- 教师图书管理员
    图书管理员 <|-- 系统管理员
    系统管理员 "1"-- "1..*"学生图书管理员
    系统管理员 "1"-- "1..*"教师图书管理员
    教师图书管理员 "1"-- "1..*"学生图书管理员
    @enduml