@startuml
actor 图书管理员
图书管理员->借书者:验证借书者
图书管理员->借书者:获取借书者资源限额
loop
图书管理员->资源项:获取资源项
资源项->馆藏资源:查询资源品种
图书管理员->借书记录:创建借书记录
图书管理员->资源项:借出资源
资源项->馆藏资源:可借资源数量减少
图书管理员->借书者:借书者可用资源额度减少
end
图书管理员->借书记录:打印出借书清单
@enduml