@startuml
actor 图书管理员
图书管理员->资源项:读取资源信息
资源项->借书记录:获取借书记录
资源项->馆藏资源:获取资源的种类
图书管理员->借书者:获取借书者信息
图书管理员->资源项:归还资源
资源项->馆藏资源:增加可借资源额度
图书管理员->借书记录:记录还书日期
opt 逾期
图书管理员->逾期记录:记录逾期记录
借书者-->图书管理员:支付逾期罚金
end
@enduml