@startuml
学生图书管理员 -left-> (借出图书)
学生图书管理员 -left-> (归还图书)
学生图书管理员 --> (查询图书)
教师图书管理员 --> (维护书目)
教师图书管理员 -->(借出图书)
教师图书管理员 --->(归还图书)
教师图书管理员 -->(查询图书)
系统管理员 -up->(增加图书)
系统管理员 -up->(删除图书)
系统管理员 -up->(修改图书)
系统管理员 -up->(查询图书)
系统管理员 -up->(日志查看)
系统管理员 -up->(用户修改)
系统管理员 -up->(系统维护)
学生 -down->(查询图书)
学生 -right->(预定图书)
学生 -right->(取消预定)
学生 -right->(查询自己借阅情况)
学生 -right->(查询欠费情况)
教师 -down->(查询图书)
教师 -->(预定图书)
教师 -->(取消预定)
教师 -->(查询自己借阅情况)
教师 -->(查询欠费情况)
教师 -->(查询自己学生借阅情况)
@enduml