    @startuml
    |读者|
    start
    :反馈书籍破损或丢失;
    |图书管理员|
    :处罚读者;
    fork
    |读者|
    :缴纳罚金]
    fork again
    |图书管理员|
    :处理图书;
    fork end
    |图书管理员|
    :反馈书籍破损或丢失;
    |系统管理员|
    :删除图书]
    stop
    @enduml